server {
    listen 80;
    server_name api.d-box.tech sse.d-box.tech;
    access_log off;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.d-box.tech;
    access_log off;

    ssl_certificate /etc/letsencrypt/live/api.d-box.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.d-box.tech/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    server_name sse.d-box.tech;
    access_log off;

    ssl_certificate /etc/letsencrypt/live/sse.d-box.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sse.d-box.tech/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:8081;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 1h;
    }
}
